import { StyleSheet } from "react-native";
import colors from "../config/colors";

export const styles = StyleSheet.create({
          addressStyle: {
            fontSize: 15,
            fontWeight: 'bold',
            textAlign: "justify",
            marginLeft: 17,
            color: '#000000',
            marginTop: 10,
            flex: 1,
          },       
          headerBackButton: {
           marginLeft: 24,
         },
         container: {
           flex: 1,
           height: "100%",
           flexDirection: "column",
           justifyContent: "center",
           backgroundColor: "#fff",
           paddingHorizontal: 30,
           borderRadius: 10,
         },
         containerText: {
           flex: 1,
           width:'100%',
           flexDirection: "row",
         },
         copyButton: {
            textAlign:'right',
            flex: 1,
          },
          caraPembayaranButton: {
            marginTop:20,
            textAlign:'center',
            flex: 1,
          },
         line: {
            width: "100%",
            height: 10,
            backgroundColor: "#dcdcdc",
            marginTop: 20,
          },
          lineTipis: {
            width: "91.5%",
            alignSelf:'center',
            height: 1,
            backgroundColor: "#dcdcdc",
            marginTop: 10,
          },
            contentContainer: {
                paddingBottom: 100,
            },
         logo: {
           height: 147,
           width: 319,
         },
         inputsContainer: {
           backgroundColor: "#EEF2F7",
           paddingHorizontal: 16,
           paddingVertical: 24,
           marginTop: 50,
           marginBottom: 50,
           borderRadius: 20,
         },
         ButtonStyle: {
           borderRadius: 0,
           alignSelf:'center',
           height: 40,
           width:'91.5%',
           marginTop: 18,
           backgroundColor: "#00CED1",
           borderRadius: 10,
         },
         titleButtonStyle: {
           fontFamily: "WorkSans-Bold",
           fontSize: 13,
           flex: 1,
         },
         ButtonWhiteStyle: {
           borderRadius: 0,
           borderWidth: 1,
           borderColor: "#00CED1",
           alignSelf:'center',
           height: 40,
           width:'91.5%',
           marginTop: 18,
           backgroundColor: "#ffffff",
           borderRadius: 10,
         },
         titleButtonWhiteStyle: {
           fontFamily: "WorkSans-Bold",
           fontSize: 13,
           color: "#00CED1",
           flex: 1,
         }, 
          titleScreenStyle: {
            fontWeight: 'bold',
            fontSize: 16,
            textAlign: "center",
            marginLeft: 0,
            marginTop: 10,
          },
          descriptionCenterStyle: {
            fontSize: 13,
            textAlign: "center",
            marginTop: 20,
          },
          descriptionScreenStyle: {
            fontSize: 13,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 20,
          },
          descriptionPriceStyle: {
            fontSize: 13,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 10,
          },
          descriptionScreenStyleBold: {
            fontWeight: 'bold',
            color:'#000000',
            fontSize: 13,
            textAlign: "justify",
            marginTop: 10,
            marginLeft: 17,
          },
          kurirStyle: {
            fontSize: 13,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 0,
          },
          nameAddressStyle: {
            fontSize: 13,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 0,
          },
          priceStyle: {
            fontSize: 15,
            marginLeft: 17,
            textAlign: "left",
            color: "#ff4500",
            fontFamily: 'WorkSans-Bold',
            flex: 1,
          },
          TimerStyle: {
            fontSize: 15,
            marginRight: 17,
            textAlign: "right",
            color: "#ff4500",
            fontFamily: 'WorkSans-Bold',
            flex: 1,
          },
          textLinkBold: {
            fontWeight: 'bold',
            fontSize: 13,
            color: "#00CED1",
            textAlign:'right',
            marginRight: 17,
            flex: 1,
          },
          textLinkCenterBold: {
            fontWeight: 'bold',
            fontSize: 13,
            color: "#00CED1",
            textAlign:'center',
            flex: 1,
          },
          titleMerchantStyle: {
            fontSize: 13,
            textAlign: "right",
            marginRight: 17,
            color:'#000000',
            marginTop: 20,
            flex: 1,
          },
          sellPriceStyle: {
            fontSize: 13,
            textAlign: "right",
            marginRight: 17,
            color:'#000000',
            marginTop: 10,
            flex: 1,
          },
          sellPriceBold: {
            fontWeight:'bold',
            fontSize: 13,
            textAlign: "right",
            marginRight: 17,
            color:'#000000',
            marginTop: 10,
            flex: 1,
          },
          titleStyle: {
            fontFamily: 'WorkSans-Bold',
            fontSize: 15,
            textAlign: "justify",
            marginLeft: 17,
            color: '#000000',
            marginTop: 20,
          },
          totalPriceStyle: {
            fontSize: 13,
            textAlign: "right",
            marginRight: 17,
            color:'#000000',
            marginTop: 20,
            flex: 1,
          },
          totalPriceProductStyle: {
            fontSize: 13,
            textAlign: "right",
            marginRight: 17,
            color:'#000000',
            marginTop: 10,
            flex: 1,
          },
          totalTextPaymentStyle: {
            fontSize: 14,
            fontWeight:'bold',
            textAlign: "justify",
            marginLeft: 17,
            color:'#000000',
            marginTop: 15,
            flex: 1,
          },
          totalPaymentStyle: {
            fontSize: 14,
            color: "#ff4500",
            fontFamily: 'WorkSans-Bold',
            textAlign: "right",
            marginRight: 17,
            marginTop: 15,
            flex: 1,
          },
          titleModalStyle: {
            fontFamily: 'WorkSans-Bold',
            fontSize: 15,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 20,
          },
          titleStoreStyle: {
            fontSize: 14,
            fontWeight:'bold',
            textAlign: "justify",
            marginLeft: 17,
            color:'#000000',
            marginTop: 15,
            flex: 1,
          },
          titleProductStyle: {
            fontSize: 14,
            fontWeight:'bold',
            textAlign: "justify",
            marginLeft: 17,
            color:'#000000',
            marginTop: 10,
            flex: 1,
          },
          qtyPriceStyle: {
            fontSize: 13,
            textAlign: "left",
            marginLeft: 17,
            color:'#000000',
            marginTop: 0,
            flex: 1,
          },
          iconContainerStyle: {
            marginTop: 15,
            marginLeft: 20,
          },
          
});
