import { StyleSheet } from "react-native";
import colors from "../config/colors";

export const stylesButton = StyleSheet.create({
  container: {
    flex: 1,
    marginHorizontal: 16,
    textAlign: "center",
    alignContent: "center",
    bottom: 15,
  },
  title: {
    textAlign: "center",
    marginVertical: 8,
  },
  fixToText: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sizeButtonStyle: {
    borderLeftWidth: 1,
    flex: 43,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  titleButtonStyleSize: {
    marginRight: 16,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  productTitleSize: {
    fontFamily: "Roboto",
    fontSize: 12,
  },
  tabsContainer: {
    marginTop: 16,
  },
  tabButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  titleTabButton: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: "#000",
    fontWeight: "bold",
  },
  separator: {
    marginVertical: 8,
    borderBottomColor: "#737373",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
});

export const styles = StyleSheet.create({
  headerBackButton: {
    marginLeft: 24,
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
  },
  contentContainer: {
    paddingBottom: 100,
  },
  swiperPicContainer: {
    height: 350,
    justifyContent: "center",
    marginTop: 8,
  },
  productSwiperPic: {
    height: 350,
    justifyContent: "center",
    marginTop: 8,
  },
  paginationStyle: {
    marginVertical: 0,
    bottom: -22,
  },
  paginationStyleItem: {
    width: 5,
    height: 5,
    marginHorizontal: 8,
  },
  priceRow: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 50,
    textAlign: "center",
  },
  actualPrice: {
    fontFamily: "Roboto",
    fontSize: 15,
    color: "red",
    // marginRight: 8,
  },
  oldPrice: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: "#646464",
    textDecorationLine: "line-through",
    color: "#000",
    // marginRight: 5,
  },
  stock: {
    marginTop: 10,
    color: "#000",
    paddingTop: -40,
    fontSize: 12,
  },
  productContent: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  productTitle: {
    maxWidth: 300,
    fontFamily: "Roboto",
    fontSize: 16,
    textAlign: "center",
    marginTop: 20,
    fontWeight: "bold",
    color: "#000",
  },
  productfull: {
    fontFamily: "Roboto",
    fontSize: 15,
    textAlign: "justify",
    paddingTop: 10,
    color: "#000",
  },
  titleproduct: {
    fontWeight: "bold",
    marginTop: 10,
    color: "#000",
  },
  productDesc: {
    marginVertical: 0,
    fontFamily: "Roboto",
    fontSize: 12,
    textAlign: "center",
    marginBottom: 10,
    paddingTop: -50,
    color: "#000",
  },
  attributeContainer: {
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    borderTopWidth: 1,
    borderTopColor: "#000",
    paddingVertical: 24,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sizeButtonStyle: {
    borderLeftWidth: 1,
    flex: 43,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  titleButtonStyleSize: {
    marginRight: 16,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  productTitleSize: {
    fontFamily: "Roboto",
    fontSize: 18,
  },
  tabsContainer: {
    marginTop: 16,
  },
  tabButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  titleTabButton: {
    fontFamily: "Roboto",
    fontSize: 15,
    color: "#000",
  },
  relatedItemsHeadingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 32,
  },
  relatedItemsHeading: {
    textAlign: "center",
    fontFamily: "Roboto",
    fontSize: 14,
    color: "#000",
  },
  relatedItemsCardsContainer: {
    marginTop: 16,
  },
  relatedItemCard: {
    marginRight: 8,
    flexDirection: "column",
    alignItems: "center",
    maxWidth: 130,
  },
  imageRelatedItem: {
    height: 130,
    width: 130,
    borderRadius: 9,
  },
  titleRelatedItem: {
    marginTop: 8,
  },
  priceRowRelated: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  actualPriceRelated: {
    fontFamily: "Roboto",
    fontSize: 9,
    color: "#F05829",
    marginRight: 8,
  },
  oldPriceRelated: {
    fontFamily: "Roboto",
    fontSize: 9,
    color: "#646464",
    textDecorationLine: "line-through",
  },
  overlayContainer: {
    backgroundColor: "rgba(0,0,0,.2)",
  },
  overlayStyle: {
    padding: 32,
    borderRadius: 0,
  },
  titleButtonStyle: {
    fontFamily: "Roboto",
    fontSize: 18,
    flex: 57,
    paddingBottom: 0,
    paddingTop: 0,
  },
  appleLogoButtonContainer: {
    borderLeftWidth: 1,
    borderLeftColor: "#fff",
    textAlign: "center",
    flexDirection: "row",
    justifyContent: "center",
    flex: 43,
  },
  priceInsideButtonText: {
    fontFamily: "Roboto",
    fontSize: 18,
    color: "#fff",
  },
  saveButton: {
    justifyContent: "space-around",
    borderRadius: 5,
    height: 55,
    marginTop: 12,
    borderColor: "#00CC99",
    backgroundColor: colors.primary,
  },
  ratingContainer: {
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  headerBackButton: {
    marginLeft: 24,
  },
  imageProductLabel: {
    alignItems: "center",
    backgroundColor: colors.secondary,
    height: 17,
    textAlign: "center",
    width: 50,
    bottom: 145,
    right: 5,
    alignSelf: "flex-end",
    borderRadius: 8,
  },
  textLabel: {
    color: "red",
    textAlignVertical: "center",
    borderRadius: 8,
    fontSize: 12,
  },
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  container1: {
    flex: 1,
    backgroundColor: colors.white,
  },
  line: {
    width: "100%",
    height: 1,
    backgroundColor: colors.black,
  },
  headerBannerContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 48,
  },
  headerTextStyle: {
    fontFamily: "Roboto",
    fontSize: 12,
    textAlign: "center",
    zIndex: 10,
    lineHeight: 30,
    textTransform: "uppercase",
    color: colors.primary,
  },
  discountBannerContainer: {
    paddingVertical: 28,
    zIndex: 1,
    height: 180,
    flex: 1,
    width: "100%",
    backgroundColor: colors.secondary,
    justifyContent: "space-around",
    marginTop: -70,
    alignItems: "flex-end",
    flexDirection: "row",
  },
  saleBannerTextContainer: {
    paddingVertical: 8,
    marginLeft: 15,
    width: "48%",
    borderBottomWidth: 1,
  },
  saleBannerText: {
    fontFamily: "Roboto",
    fontSize: 12,
  },
  rightSalesTextContainer: {},
  categoryBannerContainer: {
    marginVertical: 24,
  },
  backgroundContainer: {
    height: 350,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  textInsideCategory: {
    fontFamily: "Roboto",
    fontSize: 12,
    textAlign: "center",
    color: colors.primary,
  },
  productsGridContainer: {
    marginHorizontal: 8,
    flexDirection: "column",
  },
  productGridItem: {
    flex: 0.5,
    margin: 5,
    borderRadius: 10,
    backgroundColor: colors.white,
    elevation: 6,
  },
  cardMenu: {
    height: 25,
    width: 25,
    margin: 5,
  },
  imageProductGridItem: {
    height: 150,
    borderRadius: 9,
  },
  priceRowRelated: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  actualPriceRelated: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: "red",
    marginRight: 8,
  },
  oldPriceRelated: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: colors.gray,
    textDecorationLine: "line-through",
  },
  titleProductGridItemContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 3,
    fontWeight: "bold",
  },
  titleProductGridItem: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    maxWidth: 130,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  buttonPlusMinus: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "space-between",
  },
  buttonWrapper: {
    flexDirection: "column",
    flex: 1,
  },
  titleButtonStyle: {
    fontFamily: "Roboto",
    fontSize: 12,
    flex: 2,
    paddingBottom: 0,
    paddingTop: 0,
  },
  appleLogoButtonContainer: {
    borderLeftWidth: 1,
    borderLeftColor: colors.white,
    textAlign: "center",
    flexDirection: "row",
    justifyContent: "center",
    flex: 1,
  },
  priceInsideButtonText: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: colors.white,
  },
  categoryDiscountBanner: {
    backgroundColor: colors.red,
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 0,
    paddingHorizontal: 32,
    paddingVertical: 40,
  },
  titleCategoryDiscountBanner: {
    textAlign: "left",
    fontFamily: "Roboto",
    fontSize: 12,
    color: colors.black,
  },
  brandsContainer: {
    backgroundColor: colors.gray,
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  brandsHeaderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    alignItems: "center",
    paddingVertical: 16,
  },
  brandsHeaderText: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: colors.black,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 16,
  },
  brandsHeaderButton: {
    backgroundColor: "transparent",
    padding: 0,
  },
  tagsContainer: {
    paddingVertical: 26,
  },
  tagStyle: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 13,
    borderWidth: 1,
    marginRight: 10,
    marginBottom: 10,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  newArrivalsContainer: {
    marginTop: 32,
  },
  imageProductGridItemFirst: {
    width: "100%",
    height: 390,
    position: "absolute",
  },
  actualPriceRelatedFirst: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: colors.black,
  },
  titleProductGridItemFirst: {
    maxWidth: 130,
    fontFamily: "Roboto",
    fontSize: 13,
    textAlign: "center",
  },
  priceRow: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 12,
    fontWeight: "bold",
    color: colors.black
  },
  actualPrice: {
    fontFamily: "Roboto",
    fontSize: 12,
    color: colors.primary,
    right: 1,
    fontWeight: "bold"
  },
  oldPrice: {
    fontFamily: "Roboto",
    fontSize: 9,
    color: colors.gray,
    textDecorationLine: "line-through",
    left: 1,
  },
  // SearchInput Style //
  CariFilter: {
    alignSelf: "center",
    backgroundColor: colors.secondary,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginTop: 10,
    marginBottom: 20,
    marginLeft: 10,
    marginRight: 10,
  },
  Cari: {
    borderColor: colors.primary,
    margin: 5,
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 5,
    width: "50%",
    height: 47,
    alignSelf: "flex-end",
  },
  CariSarana: {
    // borderColor: colors.primary,
    margin: 5,
    // borderWidth: 1,
    // borderStyle: "solid",
    // borderRadius: 5,
    // width: "50%",
    height: 47,
    alignSelf: "flex-end",
  },
  IsiCari: {
    backgroundColor: colors.white,
    width: "55%",
    margin: 5,
    textAlign: "center",
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 10,
    height: 38,
    color: colors.primary,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  IsiCariSarana: {
    backgroundColor: colors.white,
    width: "55%",
    margin: 5,
    textAlign: "center",
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 10,
    height: 38,
    color: colors.primary,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  IsiCariHistory: {
    backgroundColor: colors.white,
    width: "100%",
    margin: 5,
    paddingHorizontal: 10,
    textAlign: "center",
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 10,
    height: 38,
    color: colors.primary,
    fontFamily: "Roboto",
    fontSize: 12,
  },
  ListEmpty: {
    marginTop: 25,
  },
  TextEmpty: {
    textAlign: "center",
    color: "black",
  },
  // SearchInput Style //
  productCountButtons: {
    width: "99%",
    padding: 3,
    flexDirection: "column",
    justifyContent: "space-between",
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "transparent",
    flexDirection: "row",
  },
  plusButton: {
    width: 28,
    height: 30,
    borderRadius: 0,
    backgroundColor: colors.secondary,
  },
  minusButton: {
    width: 28,
    height: 30,
    borderRadius: 0,
    backgroundColor: colors.secondary,
  },
  titleButtonStyle: {
    fontFamily: "Roboto",
    fontSize: 12,
    flex: 2,
    paddingBottom: 0,
    paddingTop: 0,
    alignItems: "center",
  },
  buttonBuy: {
    backgroundColor: colors.secondary,
    height: 27,
    width: "98%",
    alignItems: "center",
  },
  linkCard: {
    alignItems: "center",
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.primary,
  },
  textLabelType: {
    color: "white",
    textAlignVertical: "center",
    textAlign: "center",
    height: 20,
    marginLeft: 10,
    marginRight: 10,
  },
  typeLabel: {
    flex: 1,
    alignSelf: "flex-start",
    backgroundColor: "#00CED1",
    height: 25,
    borderRadius: 15,
  },
  linePrimary: {
    flex: 1,
    height: 1,
    backgroundColor: colors.white,
    elevation: 3,
    marginBottom: 5,
    marginTop: 5,
  },
  linkCardOut: {
    alignItems: "center",
    flex: 1,
    margin: 5,
    justifyContent: "space-around",
    alignContent: "center",
  },
  linkContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: -45,
    marginBottom: 5,
    alignSelf: "center",
  },
  linkText: {
    fontFamily: "Roboto",
    flex: 1,
    fontSize: 12,
    color: colors.primary,
    textAlign: "center",
  },
  icon: {
    justifyContent: "center",
  },
  verticalLine: {
    borderLeftWidth: 1,
    borderRightColor: colors.black,
    marginHorizontal: 16,
  },
  blankSpace: {
    borderLeftWidth: 0,
    borderRightColor: colors.white,
    marginHorizontal: 16,
    alignItems: "center",
    // position: center,
    // left: 30,
  },

  searchBox: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 10,
    color: colors.gray,
    flexDirection: "row",
    fontSize: 12,
    height: 43,
    margin: 8,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
});
