import { StyleSheet } from "react-native";
import colors from "../config/colors";

export const styles = StyleSheet.create({
         headerBackButton: {
           marginLeft: 24,
         },
         container: {
           flex: 1,
           height: "100%",
           flexDirection: "column",
           justifyContent: "center",
           backgroundColor: "#fff",
           paddingHorizontal: 30,
           borderRadius: 10,
         },
         containerText: {
           flex: 10,
           width:'100%',
           flexDirection: "row",
           backgroundColor: "#fff",
         },
         copyButton: {
            textAlign:'right',
            flex: 1,
          },
          caraPembayaranButton: {
            marginTop:20,
            textAlign:'center',
            flex: 1,
          },
         line: {
            width: "100%",
            height: 10,
            backgroundColor: "#dcdcdc",
            marginTop: 20,
          },
          lineTipis: {
            width: "91.5%",
            alignSelf:'center',
            height: 1,
            backgroundColor: "#dcdcdc",
            marginTop: 10,
          },
            contentContainer: {
                paddingBottom: 100,
            },
         logo: {
           height: 147,
           width: 319,
         },
         inputsContainer: {
           backgroundColor: "#EEF2F7",
           paddingHorizontal: 16,
           paddingVertical: 24,
           marginTop: 50,
           marginBottom: 50,
           borderRadius: 20,
         },
         ButtonStyle: {
           borderRadius: 0,
           alignSelf:'center',
           height: 40,
           width:'91.5%',
           marginTop: 18,
           backgroundColor: "#00CED1",
           borderRadius: 10,
         },
         titleButtonStyle: {
           fontFamily: "WorkSans-Bold",
           fontSize: 13,
           flex: 1,
         },
         ButtonWhiteStyle: {
           borderRadius: 0,
           borderWidth: 1,
           borderColor: "#00CED1",
           alignSelf:'center',
           height: 40,
           width:'91.5%',
           marginTop: 18,
           backgroundColor: "#ffffff",
           borderRadius: 10,
         },
         titleButtonWhiteStyle: {
           fontFamily: "WorkSans-Bold",
           fontSize: 13,
           color: "#00CED1",
           flex: 1,
         }, 
          titleScreenStyle: {
            fontWeight: 'bold',
            fontSize: 16,
            textAlign: "center",
            marginLeft: 0,
            marginTop: 10,
          },
          descriptionCenterStyle: {
            fontSize: 13,
            textAlign: "center",
            marginTop: 20,
          },
          descriptionScreenStyle: {
            fontSize: 13,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 20,
          },
          descriptionScreenStyleBold: {
            fontWeight: 'bold',
            fontSize: 13,
            textAlign: "justify",
            marginLeft: 17,
          },
          ImageMerchantStyle: {
            padding: 10,
            margin: 5,
            alignItems:'flex-end',
            height: 15,
            width: 50,
            marginTop: 20,
            flex: 1,
          },
          kodeStyleBold: {
            fontWeight: 'bold',
            fontSize: 15,
            textAlign: "justify",
            marginLeft: 17,
          },
          priceStyle: {
            fontSize: 15,
            marginLeft: 17,
            textAlign: "left",
            color: "#ff4500",
            fontFamily: 'WorkSans-Bold',
            flex: 1,
          },
          TimerStyle: {
            fontSize: 15,
            marginRight: 17,
            textAlign: "right",
            color: "#ff4500",
            fontFamily: 'WorkSans-Bold',
            flex: 1,
          },
          textLinkBold: {
            fontWeight: 'bold',
            fontSize: 13,
            color: "#00CED1",
            textAlign:'right',
            marginRight: 17,
            flex: 1,
          },
          textLinkCenterBold: {
            fontWeight: 'bold',
            fontSize: 13,
            color: "#00CED1",
            textAlign:'center',
            flex: 1,
          },
          titleMerchantStyle: {
            fontFamily: 'WorkSans-Bold',
            fontSize: 15,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 20,
          },
          titleModalStyle: {
            fontFamily: 'WorkSans-Bold',
            fontSize: 16,
            textAlign: "justify",
            marginLeft: 17,
            marginTop: 15,
            marginBottom: 15,
          },
          iconContainerStyle: {
            marginTop: 15,
            marginLeft: 20,
          },
          
});
